MVC.Net/PSoft.POS.Web.UI/Controllers/UserAjaxController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PSoft.EfTest.DataAccess.EFDB;
using PSoft.POS.Web.UI.Bases;
using WebGrease.Activities;

namespace PSoft.POS.Web.UI.Controllers
{
    public class UserAjaxController : BaseController
    {
        public ActionResult Manager()
        {
            // User_Info user=new User_Info();
            // Country 
            return View();
        }
         
        public ActionResult AddEdit(int id=0)
        {

            //todo check validation
            User_Info user=new User_Info();
            if (id>0)
            {
                user = DbContext.User_Info.SingleOrDefault(x => x.Id == id);
            }
            ViewBag.Success = TempData["Success"];
            return View(user);
        }

        private bool IsValidToSaveUser(User_Info newObj, out string error)
        {
            error = "";

            if (!newObj.Name.IsValid())
            {
                error += "Name is not valid.";
                return false;
            }
            if (newObj.Name.Length > 255)
            {
                error += "Name exceeded its maximum length 255.";
                return false;
            }


            if (newObj.CountryId == null)
            {
                error += "Country isnt valid .";
                return false;
            }
            if (newObj.CountryId < 1)
            {
                error += "Country isn't valid.";
                return false;
            }


            return true;
        }
        //[HttpPost]
        //public ActionResult AddEdit(User_Info user)
        //{
        //    try
        //    {
        //        string error = string.Empty;
        //        //int id = Request
        //        //todo check validation
        //        if (!IsValidToSaveUser(user,out error))
        //        {
        //            ViewBag.Error = "Attention please! User saving faild." + error;
        //            TempData["Error"] = "Attention please! User saving faild." + error;
        //            return View();
        //        }
        //        User_Info dbuser = DbContext.User_Info.SingleOrDefault(x => x.Id == user.Id);
        //        //DbContext.User_Info.Add(user);
        //        if (dbuser == null)
        //        {
        //            //create
        //            DbContext.User_Info.Add(user);
        //            DbContext.SaveChanges();
        //            //var url = Url.Action("AddEdit", "User", new { Id = user.Id });
        //            //return Redirect(url);
        //            TempData["Success"] = "User Created Successfully";
        //            //ViewBag.Success = "User Created Successfully";
        //            return RedirectToAction("AddEdit", "User", new { Id = user.Id });
        //        }
        //        else
        //        {
        //            //edit
        //            dbuser.Email = user.Email;
        //            dbuser.CountryId = user.CountryId;
        //            dbuser.GenderEnumId = user.GenderEnumId;
        //            dbuser.Name = user.Name;
        //            DbContext.SaveChanges();
        //            //TempData["Success"] = "User Updated Successfully";
        //            ViewBag.Success = "User Updated Successfully";
        //            ModelState.Clear();
        //            return View(user);
        //        }

        //    }
        //    catch (Exception ex)
        //    {
        //        //LogError()
        //        ViewBag.Error = "Attention please! User creation faild, Try again."+ ex.ToString();
        //        return View();
        //    }

           
        //}

        [HttpPost]
        public JsonResult Save(User_Info user)
        {
            var result = HttpResult.GetNew();
            try
            {
                string error = string.Empty;
                //int id = Request
                //todo check validation
                if (!IsValidToSaveUser(user, out error))
                {
                    result.Data = "" + error;
                    result.HasError = true;
                    return Json(result) ;
                }
                User_Info dbuser = DbContext.User_Info.SingleOrDefault(x => x.Id == user.Id);

                if (dbuser == null)
                {
                    //create
                    DbContext.User_Info.Add(user);
                    DbContext.SaveChanges();
                    result.Data = user.Id;
                    return Json(result);
                }
                else
                {
                    //edit
                    dbuser.Email = user.Email;
                    dbuser.CountryId = user.CountryId;
                    dbuser.GenderEnumId = user.GenderEnumId;
                    dbuser.Name = user.Name;
                    DbContext.SaveChanges();
                    result.Data = user.Id;
                    return Json(result);
                }

            }
            catch (Exception ex)
            {
                //LogError()
                result.Data = "" + ex.ToString();
                result.HasError = true;
                return Json(result);
            }


        }

        public ActionResult List()
        {
            var userList = DbContext.User_Info.Include(x=>x.Country).ToList();
            return View(userList);
        }
        public bool Delete(int id)
        {
            //todo check validation
            if (id > 0)
            {
                EfTestDbContext DbContext = new EfTestDbContext();
                var user = DbContext.User_Info.SingleOrDefault(x => x.Id == id);
                if (user != null)
                {
                    DbContext.User_Info.Remove(user);
                    DbContext.SaveChanges();
                    return true;
                    // TempData["success"] = "User Deleted Successfully";
                }
            }
            return  false;

        }
    }
}

MVC.Net/PSoft.POS.Web.UI/Controllers/UserAngularController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using PSoft.EfTest.DataAccess.EFDB;
using PSoft.POS.Web.UI.Bases;
using PSoft.POS.Web.UI.Models;
using WebGrease.Activities;

namespace PSoft.POS.Web.UI.Controllers
{
    public class UserAngularController : BaseController
    {
        
        #region MVC Actions
        public ActionResult Manager()
        {
            return View();
        }
        [ChildActionOnly]
        public ActionResult AddEdit(int id = 0)
        {
           return View();
        }
        [ChildActionOnly]
        public ActionResult List()
        {
           
            return View();
        }
        #endregion

        #region Angular Api
        public string GetUserList()
        {
            var result = HttpResult.GetNew();
            try
            {
                string error = string.Empty;

              

                List<User_Info> userList = DbContext.User_Info.Include(x => x.Country).ToList();//

                List<UserJson> userJsonList = UserJson.ToJson(userList);


                result.Data = userJsonList;
                return ToJson(result);
            }
            catch (Exception ex)
            {
                //LogError()
                result.Errors.Add(ex.ToString()); 
                result.HasError = true;
                return ToJson(result);
            }


        }

        public string GetDataExtra()
        {
            return null;
        }
        public string GetUserById(int id = 0)
        {
            var result = HttpResult.GetNew();
            User_Info user = null;
            if (id > 0)
            {
                user = DbContext.User_Info.SingleOrDefault(x => x.Id == id);
            }
            if (user==null)
            {
                user = User_Info.GetNew();
            }
            result.Data = user;
            result.DataBag.CountryList = DbContext.Country.ToList();
            result.DataBag.GenderEnumList= EnumUtil.GetEnumList(typeof(User_Info.GenderEnum));

            return ToJson(result);
        }
        private bool IsValidToSaveUser(User_Info newObj, out string error)
        {
            error = "";

            if (!newObj.Name.IsValid())
            {
                error += "Name is not valid.";
                return false;
            }
            if (newObj.Name.Length > 255)
            {
                error += "Name exceeded its maximum length 255.";
                return false;
            }


            if (newObj.CountryId == null)
            {
                error += "Country isnt valid .";
                return false;
            }
            if (newObj.CountryId < 1)
            {
                error += "Country isn't valid.";
                return false;
            }


            return true;
        }
        [HttpPost]
        public string Save(User_Info user)
        {
            var result = HttpResult.GetNew();
            try
            {
                string error = string.Empty;
                //int id = Request
                //todo check validation
                if (!IsValidToSaveUser(user, out error))
                {
                    result.Errors.Add(error) ;
                    result.HasError = true;
                    return ToJson(result);
                }
                User_Info dbuser = DbContext.User_Info.SingleOrDefault(x => x.Id == user.Id);

                if (dbuser == null)
                {
                    //create
                   
                    DbContext.User_Info.Add(user);
                    DbContext.SaveChanges();
                    result.Data = user;
                    return ToJson(result);
                }
                else
                {
                    //edit
                    dbuser.Email = user.Email;
                    dbuser.CountryId = user.CountryId;
                    dbuser.GenderEnumId = user.GenderEnumId;
                    dbuser.Name = user.Name;
                    DbContext.SaveChanges();
                    result.Data = user;
                    return ToJson(result);
                }

            }
            catch (Exception ex)
            {
                //LogError()
                result.Errors.Add(ex.ToString());
                result.HasError = true;
                return ToJson(result);
            }


        }
        public string Delete(int id)
        {
            //todo check validation
            var result = HttpResult.GetNew();
         
            result.HasError = true;
            try
            {
                string error = string.Empty;
                if (id > 0)
            {
                EfTestDbContext DbContext = new EfTestDbContext();
                var user = DbContext.User_Info.SingleOrDefault(x => x.Id == id);
                if (user != null)
                {
                    DbContext.User_Info.Remove(user);
                    DbContext.SaveChanges();
                        result.HasError = false;
                        return ToJson(result);
               }
                    else
                    {
                        result.Errors.Add("User Not Found.");
                    }

                }
                else
                {
                    result.Errors.Add("Invalid User.");
                }
                return ToJson(result);
            }
            catch (Exception ex)
            {
                //LogError()
                result.Errors.Add(ex.ToString());
                result.HasError = true;
                return ToJson(result);
    }

}
        #endregion



    }
}

MVC.Net/PSoft.POS.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
</head>
<body>
    @Html.Partial("_TopMenu")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/bootstrap-datetimepicker/js/moment.min.js"></script>
    <script src="~/Content/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
        @RenderSection("scripts", required: false)
</body>
</html>

MVC.Net/PSoft.POS.Web.UI/Views/Shared/_LayoutAngular.cshtml
<!DOCTYPE html>
<html ng-app="myApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
</head>
<body>
    @Html.Partial("_TopMenu")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/bootstrap-datetimepicker/js/moment.min.js"></script>
    <script src="~/Content/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Content/angular/angular.js"></script>

    <script name="angular">
    //https://www.codeproject.com/Articles/806029/Getting-started-with-AngularJS-and-ASP-NET-MVC-Par
    //https://www.youtube.com/watch?v=s3qZF4jhgDo&index=1&list=PLYxzS__5yYQmX2bItSRCqwiQZn5dIL1gt
    var myApp = angular.module('myApp',[]);

    </script>
@RenderSection("scripts", required: false)


</body>
</html>

MVC.Net/PSoft.POS.Web.UI/Views/Shared/_TopMenu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Jquery Test", "Manager", "UserAjax")</li>
                <li>@Html.ActionLink("Angular Test", "Manager", "UserAngular")</li>
                @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>